<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="TCS" failures="1" tests="1" name="Test(failed)" time="0.103" errors="0" timestamp="2023-12-15T00:52:26 IST">
  <testcase classname="TestNG_AllPrg.FirstTestNG2" name="searchCust" time="0.023">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at TestNG_AllPrg.FirstTestNG2.searchCust(FirstTestNG2.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- searchCust -->
  <testcase classname="TestNG_AllPrg.FirstTestNG2" name="teardown" time="0.0">
    <ignored/>
  </testcase> <!-- teardown -->
  <testcase classname="TestNG_AllPrg.FirstTestNG2" name="setup" time="0.0">
    <ignored/>
  </testcase> <!-- setup -->
</testsuite> <!-- Test(failed) -->
